encoder_features:
  backbone: "cnn"
  backbone_cfg: 
    backbone: "efficientnet_v2_s"
    hidden_dim: 64
    dropout_rate: 0.01
    output_dim: 2
  save_dir: "/home/noedia/links/scratch/crl/experiments/rings/models/encoder_features"

encoder_labels:
  backbone: "mlp"
  backbone_cfg: 
    input_dim: 2
    layer_widths: [8, 8, 8]
    output_dim: 2
    activation_func: "silu"
    activate_final: False
  save_dir: "/home/noedia/links/scratch/crl/experiments/rings/encoder_labels"

data:
  path: "/home/noedia/links/scratch/crl/experiments/rings/data"
  data_split: null

trainer:
  epochs: 50  
  optimizer: "adam"
  batch_size: 512
  lr: 1e-3
  seed: 42
  device: "auto"
  normalize: true
  transform: null